params = {'vertex_nums' : 1200,
          'feature_nums':30000,
          'feature_dim':512,
          'alpha':10,
          'eta':0.1,
          'gpu_nums':5,
          'max_iter':1000,
          'class' : 200,
          'test_feature_nums' : 300,
          'n_way' : 5,
          'k_shot' : 5,
          'lambda_i':10,
          'lambda_f':0.01,
          'epsilon_i':0.1,
          'epsilon_f':0.005
}
